const CONSTANTS = {
  ADD_TEST: "ADD_TEST",
  REMOVE_TEST: "REMOVE_TEST",
  ADD_APPENDIX: "ADD_APPENDIX",
  REMOVE_APPENDIX_SUBTEST: "REMOVE_APPENDIX_SUBTEST",
  ADD_RECOMMENDATION: "ADD_RECOMMENDATION",
  REMOVE_RECOMMENDATION: "REMOVE_RECOMMENDATION",
  SHOW_DOMAIN: "SHOW_DOMAIN",
  HIDE_DOMAIN: "HIDE_DOMAIN",
  SHOW_SUBDOMAIN: "SHOW_SUBDOMAIN",
  HIDE_SUBDOMAIN: "HIDE_SUBDOMAIN",
  SHOW_TESTS: "SHOW_TESTS",
  HIDE_TESTS: "HIDE_TESTS",
  SHOW_SUMMARY: "SHOW_SUMMARY",
  HIDE_SUMMARY: "HIDE_SUMMARY"
};

export default CONSTANTS;

export const ADD_TEST = "ADD_TEST";
export const REMOVE_TEST = "REMOVE_TEST";
export const ADD_APPENDIX = "ADD_APPENDIX";
export const REMOVE_APPENDIX_SUBTEST = "REMOVE_APPENDIX_SUBTEST";
export const ADD_RECOMMENDATION = "ADD_RECOMMENDATION";
export const REMOVE_RECOMMENDATION = "REMOVE_RECOMMENDATION";
