const CONSTANTS = {
  ADD_TEST: 'ADD_TEST',
  REMOVE_TEST: 'REMOVE_TEST',
  ADD_APPENDIX: 'ADD_APPENDIX',
  ADD_APPENDIX_DOMAIN: 'ADD_APPENDIX_DOMAIN',
  REMOVE_APPENDIX_DOMAIN: 'REMOVE_APPENDIX_DOMAIN',
  ADD_APPENDIX_SUBTEST: 'ADD_APPENDIX_SUBTEST',
  REMOVE_APPENDIX_SUBTEST: 'REMOVE_APPENDIX_SUBTEST',
  ADD_APPENDIX_TEST: 'ADD_APPENDIX_TEST',
  REMOVE_APPENDIX_TEST: 'REMOVE_APPENDIX_TEST',
  ADD_APPENDIX_PARENTSCALE: 'ADD_APPENDIX_PARENTSCALE',
  REMOVE_APPENDIX_PARENTSCALE: 'REMOVE_APPENDIX_PARENTSCALE',
  ADD_RECOMMENDATION: 'ADD_RECOMMENDATION',
  REMOVE_RECOMMENDATION: 'REMOVE_RECOMMENDATION',
  ADD_SUB_RECOMMENDATION: 'ADD_SUB_RECOMMENDATION',
  REMOVE_SUB_RECOMMENDATION: 'REMOVE_SUB_RECOMMENDATION',
  ADD_SUB_SUB_RECOMMENDATION: 'ADD_SUB_SUB_RECOMMENDATION',
  SHOW_DOMAIN: 'SHOW_DOMAIN',
  HIDE_DOMAIN: 'HIDE_DOMAIN',
  SHOW_SUBDOMAIN: 'SHOW_SUBDOMAIN',
  HIDE_SUBDOMAIN: 'HIDE_SUBDOMAIN',
  SHOW_TESTS: 'SHOW_TESTS',
  HIDE_TESTS: 'HIDE_TESTS',
  SHOW_SUMMARY: 'SHOW_SUMMARY',
  HIDE_SUMMARY: 'HIDE_SUMMARY',
  SHOW_DOMAINS_TESTS: 'SHOW_DOMAINS_TESTS',
  HIDE_DOMAINS_TESTS: 'HIDE_DOMAINS_TESTS',
  HANDLE_MATCHES: 'HANDLE_TEST_MATCH',
  REMOVE_TESTS: 'REMOVE_TESTS',
  ADD_TESTS: 'ADD_TESTS',
  SHOW_TEST: 'SHOW_TEST',
  ADD_PATIENT_AGE: 'ADD_PATIENT_AGE',
  ADD_DSM_CODE: 'ADD_DSM_CODE',
  REMOVE_DSM_CODE: 'REMOVE_DSM_CODE',
  ADD_COPY_FORWARD_DATA: 'ADD_COPY_FORWARD_DATA',
  REMOVE_COPY_FORWARD_DATA: 'REMOVE_COPY_FORWARD_DATA',
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
};

export default CONSTANTS;

export const ADD_TEST = 'ADD_TEST';
export const REMOVE_TEST = 'REMOVE_TEST';
export const ADD_APPENDIX = 'ADD_APPENDIX';
export const REMOVE_APPENDIX_SUBTEST = 'REMOVE_APPENDIX_SUBTEST';
// export const ADD_RECOMMENDATION = 'ADD_RECOMMENDATION';
export const REMOVE_RECOMMENDATION = 'REMOVE_RECOMMENDATION';
