const CONSTANTS = {
  ADD_TEST: "ADD_TEST",
  REMOVE_TEST: "REMOVE_TEST",
  ADD_APPENDIX: "ADD_APPENDIX",
  REMOVE_APPENDIX_SUBTEST: "REMOVE_APPENDIX_SUBTEST",
  ADD_RECOMMENDATION: "ADD_RECOMMENDATION",
  REMOVE_RECOMMENDATION: "REMOVE_RECOMMENDATION"
};

export default CONSTANTS;

export const ADD_TEST = "ADD_TEST";
export const REMOVE_TEST = "REMOVE_TEST";
export const ADD_APPENDIX = "ADD_APPENDIX";
export const REMOVE_APPENDIX_SUBTEST = "REMOVE_APPENDIX_SUBTEST";
export const ADD_RECOMMENDATION = "ADD_RECOMMENDATION";
export const REMOVE_RECOMMENDATION = "REMOVE_RECOMMENDATION";
